### PR TITLE
Use server_version_num instead of server_version

### PR DESCRIPTION
**Pull request by ianp**
Resolves https://github.com/db-migrate/pg/issues/32.

Signed-off-by: Ian Phillips <ianp@ianp.org>

### CODE REVIEW

**Comment by ianp** [comment]
No idea what commitlint it wittering on about, there is clearly a commit message present??? Silly robot.

**Comment by wzrdtales** [comment]
It is about commit conventions, I thought it would have had a link to the docs though.

https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular

**Comment by wzrdtales** [comment]
`show server_version_num` seems to be not valid on all postgres databases.

```
HOW server_version_num;
pq: unknown variable: "server_version_num"
```

**Comment by wzrdtales** [comment]
We will need something else, that does no break.

**Comment by wzrdtales** [comment]
Either a different approach, or falling back if `_num` is not available.

**Comment by ianp** [comment]
Looks like `server_version_num` is only in PG versions 8.2 and above, but since the min version is 9.1.0 would an acceptable fallback be to just set `options.ifNotExists = false` in a catch? Otherwise I can fallback to using `server_version` in a catch, but that seems redundant.

**Comment by wzrdtales** [comment]
It is not just pg, but all dbs that depend on the pg wire protocol, thus this would break much more though.

**Comment by ianp** [comment]
I think that this should work for both PG and non-PG databases now. I still need to clean up that first commit message to keep the linter happy. Also, I think that I could make it more readable by factoring out a couple of helper functions, but I wanted to check the basic approach with you first.

**Comment by wzrdtales** [comment]
Awesome, I will review a bit later when I've got a couple of quiet minutes.

**Comment by danmconrad** [comment]
Any movement on this? I'm getting the same error.

**Comment by ianp** [comment]
Let me know if there are any changes you'd like to see on this.

**Comment by mingfang** [comment]
The proposal here https://github.com/db-migrate/pg/issues/34 also works.
Add ```version = version.split(' ')[0]``` after line 172.

**Comment by wzrdtales** [comment]
Thank you for your contribution! Nothing to add here, going to release a new version of this soo :tada:

**Pull request merged**
