### PR TITLE
feat: support ifNotExists when creating a postgres db

### PR DESCRIPTION
**Pull request by andyburke**
Adds an implementation of ifNotExists for postgres when creating a database.

Unfortunately, this isn't as easy as adding some SQL. You need to use an extension, etc. I also had to update dependencies to get tests to run under a more recent version of node. Willing to work through feedback to try to get this accepted.

### CODE REVIEW

**Comment by andyburke** [comment]
Any feelings on this?

**Comment by andyburke** [comment]
Is this module still being maintained?

**Comment by wzrdtales** [comment]
It is but I am unfortunately very busy and do not always find time to invest. But I am very glad about all help and should you be willing to help maintaining this would be more than welcome!

About your changes: Please note, never upgrade vows. there is an ugly bug in it and it completely breaks that is why the version is fixated. We still need to switch to lab for testing on this repo too, I just recently migrated the mysql one though. The changes look fine otherwise too me though.

**Comment by andyburke** [comment]
I downgraded vows, but that means I cannot run the tests locally.

Let me know if there's anything else needed before this can be merged.

**Pull request merged**
